# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XO\com_easy.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EasyWindow(object):
    def setupUiEasy(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(332, 407)
        StartWindow.setMinimumSize(QtCore.QSize(332, 407))
        StartWindow.setMaximumSize(QtCore.QSize(332, 407))
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(110, 30, 300, 25))
        self.label2.setFont(font)
        self.label2.setObjectName("ToChangeLabel")
        self.box1 = QtWidgets.QPushButton(self.centralwidget)
        self.box1.setGeometry(QtCore.QRect(50, 50, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box1.setFont(font)
        self.box1.setText("")
        self.box1.setObjectName("box1")
        self.box2 = QtWidgets.QPushButton(self.centralwidget)
        self.box2.setGeometry(QtCore.QRect(140, 50, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box2.setFont(font)
        self.box2.setText("")
        self.box2.setObjectName("box2")
        self.box3 = QtWidgets.QPushButton(self.centralwidget)
        self.box3.setGeometry(QtCore.QRect(230, 50, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box3.setFont(font)
        self.box3.setText("")
        self.box3.setObjectName("box3")
        self.box4 = QtWidgets.QPushButton(self.centralwidget)
        self.box4.setGeometry(QtCore.QRect(50, 130, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box4.setFont(font)
        self.box4.setText("")
        self.box4.setObjectName("box4")
        self.box5 = QtWidgets.QPushButton(self.centralwidget)
        self.box5.setGeometry(QtCore.QRect(140, 130, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box5.setFont(font)
        self.box5.setText("")
        self.box5.setObjectName("box5")
        self.box6 = QtWidgets.QPushButton(self.centralwidget)
        self.box6.setGeometry(QtCore.QRect(230, 130, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box6.setFont(font)
        self.box6.setText("")
        self.box6.setObjectName("box6")
        self.box7 = QtWidgets.QPushButton(self.centralwidget)
        self.box7.setGeometry(QtCore.QRect(50, 210, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box7.setFont(font)
        self.box7.setText("")
        self.box7.setObjectName("box7")
        self.box8 = QtWidgets.QPushButton(self.centralwidget)
        self.box8.setGeometry(QtCore.QRect(140, 210, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box8.setFont(font)
        self.box8.setText("")
        self.box8.setObjectName("box8")
        self.box9 = QtWidgets.QPushButton(self.centralwidget)
        self.box9.setGeometry(QtCore.QRect(230, 210, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.box9.setFont(font)
        self.box9.setText("")
        self.box9.setObjectName("box9")
        self.new_game_player_mode = QtWidgets.QPushButton(self.centralwidget)
        self.new_game_player_mode.setGeometry(QtCore.QRect(50, 310, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.new_game_player_mode.setFont(font)
        self.new_game_player_mode.setObjectName("new_game_player_mode")
        StartWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 332, 21))
        self.menubar.setObjectName("menubar")
        StartWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartWindow)
        self.statusbar.setObjectName("statusbar")
        StartWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "StartWindow"))
        self.label.setText(_translate("StartWindow", "    Welcome To tic tac toe game computer mode"))
        self.new_game_player_mode.setStatusTip(_translate("StartWindow", "start a new game"))
        self.new_game_player_mode.setText(_translate("StartWindow", "New Game"))
